'use strict';
/**
 * VcdParser
 * Parses IEEE 1364 Value Change Dump (VCD) files generated by
 * Icarus Verilog, Verilator, ModelSim, Questa, VCS, etc.
 *
 * Supports:
 *   - Multi-level scope hierarchy
 *   - 1-bit scalars
 *   - Multi-bit vectors (buses)
 *   - Real values
 *   - Simulation timescale
 *   - Compressed/uncompressed VCD
 */

class VcdParser {
  static parse(vcdText) {
    const p = new VcdParser();
    return p._parse(vcdText);
  }

  _parse(text) {
    this.timescale   = '1ns';
    this.date        = '';
    this.version     = '';
    this.idToSignal  = {};   // idCode -> SignalDef
    this.signals     = {};   // fullPath -> SignalDef
    this.scopeStack  = [];
    this.currentTime = 0;
    this.hierarchy   = { name: 'root', type: 'scope', children: [], signals: [] };
    this.scopeNode   = this.hierarchy;

    // Split into tokens — VCD is whitespace-delimited
    const tokens = text.split(/\s+/).filter(Boolean);
    let   i      = 0;

    while (i < tokens.length) {
      const tok = tokens[i++];

      if (tok === '$timescale') {
        const parts = [];
        while (i < tokens.length && tokens[i] !== '$end') parts.push(tokens[i++]);
        i++; // consume $end
        this.timescale = parts.join(' ').trim();

      } else if (tok === '$date') {
        const parts = [];
        while (i < tokens.length && tokens[i] !== '$end') parts.push(tokens[i++]);
        i++;
        this.date = parts.join(' ').trim();

      } else if (tok === '$version') {
        const parts = [];
        while (i < tokens.length && tokens[i] !== '$end') parts.push(tokens[i++]);
        i++;
        this.version = parts.join(' ').trim();

      } else if (tok === '$scope') {
        const scopeType = tokens[i++] || 'module';
        const scopeName = tokens[i++] || 'scope';
        i++; // $end
        const node = { name: scopeName, type: scopeType, children: [], signals: [] };
        this._currentScopeNode().children.push(node);
        this.scopeStack.push({ name: scopeName, node });

      } else if (tok === '$upscope') {
        i++; // $end
        this.scopeStack.pop();

      } else if (tok === '$var') {
        const varType   = tokens[i++]; // wire/reg/integer/real/...
        const width     = parseInt(tokens[i++], 10);
        const idCode    = tokens[i++];
        const refName   = tokens[i++];
        // optional bit-select e.g. [3:0] or [7]
        let   bitSelect = '';
        if (tokens[i] !== '$end') { bitSelect = tokens[i++]; }
        i++; // $end

        const scopePath = this.scopeStack.map(s => s.name).join('.');
        const fullPath  = scopePath ? `${scopePath}.${refName}` : refName;

        const sig = {
          name:     refName,
          fullPath,
          idCode,
          type:     varType,
          width,
          bitSelect,
          scope:    scopePath,
          changes:  [],   // { time, value }
        };

        this.idToSignal[idCode] = sig;
        this.signals[fullPath]  = sig;
        this._currentScopeNode().signals.push(sig);

      } else if (tok === '$dumpvars' || tok === '$dumpall' || tok === '$dumpon' || tok === '$dumpoff') {
        // Initial value block — parse until $end
        while (i < tokens.length && tokens[i] !== '$end') {
          i = this._parseValueChange(tokens, i);
        }
        i++; // $end

      } else if (tok === '$enddefinitions') {
        i++; // $end

      } else if (tok === '$comment') {
        while (i < tokens.length && tokens[i] !== '$end') i++;
        i++;

      } else if (tok.startsWith('#')) {
        // Timestamp
        this.currentTime = parseInt(tok.slice(1), 10);

      } else {
        // Value change: put token back and parse
        i = this._parseValueChange(tokens, i - 1);
      }
    }

    return this._buildResult();
  }

  _parseValueChange(tokens, i) {
    const tok = tokens[i];
    if (!tok) return i + 1;

    // Scalar: 0id  1id  xid  zid  etc.
    if (/^[01xXzZuU][^\s]+/.test(tok) && tok.length > 1 && !tok.startsWith('b') && !tok.startsWith('B') && !tok.startsWith('r') && !tok.startsWith('R')) {
      const val    = tok[0].toLowerCase();
      const idCode = tok.slice(1);
      const sig    = this.idToSignal[idCode];
      if (sig) sig.changes.push({ time: this.currentTime, value: val });
      return i + 1;
    }

    // Vector: b/B followed by value, then idCode
    if (tok === 'b' || tok === 'B' || tok.startsWith('b') || tok.startsWith('B')) {
      const binVal = tok.length > 1 ? tok.slice(1) : tokens[i + 1];
      const offset = tok.length > 1 ? 0 : 1;
      const idCode = tokens[i + 1 + offset];
      const sig    = this.idToSignal[idCode];
      if (sig) sig.changes.push({ time: this.currentTime, value: binVal.toLowerCase() });
      return i + 2 + offset;
    }

    // Real: r/R followed by value, then idCode
    if (tok === 'r' || tok === 'R' || tok.startsWith('r') || tok.startsWith('R')) {
      const realVal = tok.length > 1 ? tok.slice(1) : tokens[i + 1];
      const offset  = tok.length > 1 ? 0 : 1;
      const idCode  = tokens[i + 1 + offset];
      const sig     = this.idToSignal[idCode];
      if (sig) sig.changes.push({ time: this.currentTime, value: parseFloat(realVal) });
      return i + 2 + offset;
    }

    return i + 1;
  }

  _currentScopeNode() {
    if (this.scopeStack.length === 0) return this.hierarchy;
    return this.scopeStack[this.scopeStack.length - 1].node;
  }

  _buildResult() {
    const signalList = Object.values(this.signals);
    const endTime    = signalList.reduce((max, s) => {
      if (!s.changes.length) return max;
      return Math.max(max, s.changes[s.changes.length - 1].time);
    }, 0);

    // Normalize timescale to a multiplier in ns
    const tsMultiplier = parseTimescale(this.timescale);

    return {
      metadata: {
        timescale:    this.timescale,
        tsMultiplier,
        date:         this.date,
        version:      this.version,
        endTime,
        endTimeNs:    endTime * tsMultiplier,
        signalCount:  signalList.length,
      },
      hierarchy: this.hierarchy,
      signals:   signalList.map(s => ({
        name:      s.name,
        fullPath:  s.fullPath,
        scope:     s.scope,
        idCode:    s.idCode,
        type:      s.type,
        width:     s.width,
        bitSelect: s.bitSelect,
        changes:   s.changes,
      })),
    };
  }
}

// ── Timescale parser ──────────────────────────────────────────────────────────
// Returns multiplier to convert VCD time units → nanoseconds
function parseTimescale(ts) {
  const m = ts.match(/([\d.]+)\s*(fs|ps|ns|us|ms|s)/i);
  if (!m) return 1;
  const val  = parseFloat(m[1]);
  const unit = m[2].toLowerCase();
  const map  = { fs: 1e-6, ps: 1e-3, ns: 1, us: 1e3, ms: 1e6, s: 1e9 };
  return val * (map[unit] || 1);
}

module.exports = VcdParser;
